### ISSUE TITLE
Mono "hello world" program gives  errors

### ISSUE THREAD

**Issue by dz0** [ochko/safeexec#5]
We try to adapt Websheets for C#, 
but safeexec experiments with [Hello World](http://www.mono-project.com/docs/getting-started/mono-basics/#console-hello-world) give strange errors:

cemc fork gives OLE:
```
$ ./safeexec --exec /usr/bin/mono tests/hello.exe
Output Limit Exceeded
elapsed time: 1 seconds
memory usage: 628 kbytes
```

and ochko version:
```
$ ./safeexec --exec /usr/bin/mono tests/hello.exe
CreateThread: Error creating native thread handle Resource temporarily unavailable (11)
Command exited with non-zero status (1)
elapsed time: 0 seconds
memory usage: 64 kbytes
cpu usage: 0.012 seconds
cpu usage: 0.000 seconds
```

we use Ubuntu 14.04

**Comment by ochko** [comment]
Mono runtime needs more than 1 thread. Try this:

`$ ./safeexec --nproc 3 --exec /usr/bin/mono tests/hello.exe`

**Comment by dz0** [comment]
Thanks, it helps for your version:
```
$ ./safeexec --nproc 3 --exec /usr/bin/mono tests/hello.exe
Hello Mono
OK
elapsed time: 0 seconds
memory usage: 18244 kbytes
cpu usage: 0.056 seconds
```

but still gives `Output Limit Exceeded` for cemc branch.

**Comment by ochko** [comment]
> memory usage: 18244 kbytes

If you program run a bit longer it will terminate with `Memory Limit Exceeded`. That case you could try `--mem 60000` or more.
